framework:
    secret: '%env(APP_SECRET)%'
    php_errors:
        log: true
    http_client:
        scoped_clients:
            logstash.client:
                base_uri: 'log_parser.logstash.address'
                retry_failed:
                    http_codes: [429]
                    max_retries: 10
                    delay: 1000
                    multiplier: 2
