monolog:
    channels:
        - deprecation
    handlers:
        main:
            type: stream
            path: "%kernel.logs_dir%/spreadsheet.%kernel.environment%.log"
            level: debug
            channels: ["!event"]
        console:
            type: console
            process_psr_3_messages: true
            level: info
            channels: ["!event", "!console"]
            verbosity_levels:
                VERBOSITY_NORMAL: NOTICE
                VERBOSITY_VERBOSE: INFO
