#!/bin/sh

# Checking if the image is already built and if no, building
if [[ "$(docker images -q spreadsheet:latest 2> /dev/null)" == "" ]]; then
  docker build -t spreadsheet:latest .
fi

docker run --rm \
--volume $PWD:/app \
spreadsheet:latest "$@"